#!/bin/bash

if [ -z "$1" ] ; then
    echo "ERROR: Target app not supplied."

    echo "Pin based function tracer"
    echo "Usage: pftrace <target_app>"
    exit
fi

TARGET_APP=$1

PIN_DIR="$HOME/pin/"
PIN_TOOLS_DIR="$PIN_DIR/source/tools/PFTracer/obj-intel64"
PINTOOL64="$PIN_TOOLS_DIR/PFTracer.so"

$PIN_DIR/pin -t "$PINTOOL64" -- "$TARGET_APP"
